### ISSUE TITLE
Error while creating indy wallet in mobile react-native

### ISSUE THREAD

**Issue by sairanjit** [AbsaOSS/rn-indy-sdk#11]
02-24 18:06:36.238 31678 31773 W com.sun.jna.Native: JNA: Callback org.hyperledger.indy.sdk.wallet.Wallet$1@f549fed threw the following exception
02-24 18:06:36.238 31678 31773 W com.sun.jna.Native: java.lang.UnsatisfiedLinkError: Error looking up function 'indy_get_current_error': undefined symbol: indy_get_current_error
![Screenshot from 2020-02-24 18-18-03](https://user-images.githubusercontent.com/34263716/75153690-04e02080-5732-11ea-931d-c3041425bafb.png)

**Comment by karimStekelenburg** [comment]
@sairanjit Did you manage to solve this issue? I'm running into the same problem..

**Comment by TheArhaam** [comment]
@sairanjit @karimStekelenburg I seem to be facing the same issue, any updates?

**Comment by karimStekelenburg** [comment]
@TheArhaam I am not sure what the exact fix is. But my lovely colleague Timo Glastra got it to work on Android. He has a [fork](https://github.com/TimoGlastra/rn-indy-sdk) with an `example` directory that holds a working example app that uses `rn-indy-sdk`.

You might want to compare how Indy is imported in the `onCreate()` method in [this](https://github.com/TimoGlastra/rn-indy-sdk/blob/master/example/android/app/src/main/java/com/example/MainActivity.java) file.

Hope it helps!

**Comment by TheArhaam** [comment]
@karimStekelenburg I cloned that repo and it seems to be working, thank you for that. So there is nothing wrong with the SDK from what I can tell, it's just that "indy" wasn't being imported properly in the native code right?

It's been a while since I've worked with java & android so I apologize if it's a silly question haha 😄

**Comment by karimStekelenburg** [comment]
No problem! I'm not that experienced with Android myself either, but yes that is what I suspect. I'll ping my colleague to get you a solid answer to your question. ;-)

**Comment by TimoGlastra** [comment]
As @karimStekelenburg already mentioned the SDK is working as expected. The installation guide for Android is missing some steps. The [fork I made](https://github.com/TimoGlastra/rn-indy-sdk#android) contains an update readme with the required steps. Do note however that that guide expects the binaries to be included in rn-indy-sdk, which is the case in my fork, but not the case in this repo. You'll still need to copy the binaries to `android/app/src/main/jniLibs`.

**Comment by TheArhaam** [comment]
@karimStekelenburg Haha! Thank you 😃 
@TimoGlastra Thank you for the clarification! 😄 
I was able to get it running, I was just curious as to what the issue was, your fork did help me 😄 

Also, have you tested this out with mediator/edge agents? I'm still figuring out what all can be achieved using this SDK. My end goal is to prepare an Aries Mobile Agent (AMA) that can communicate with Aries Cloud Agents (ACA), do you think it's possible at this point?

I would love to discuss this further, would it be alright if I got in touch with you over Email? 😄

**Comment by TimoGlastra** [comment]
What do you mean exactly with mediator/edge agents? Basically this SDK allows you to do everything you can do with indy SDK for NodeJS, but in React Native.

For the mobile agent part you should use [aries-framework-javascript](https://github.com/hyperledger/aries-framework-javascript) that makes use of rn-indy-sdk. Aries Framework JavaScript can be used with a cloud agent, but I haven't tested it with a mediator in between. 

I recently added aries-framework-javascript to [aries-agent-test-harness](https://github.com/hyperledger/aries-agent-test-harness) which allow it to make a connection with an ACA-Py instance.

**Comment by TheArhaam** [comment]
@TimoGlastra Oh I see 🤔, it seems like I was slightly misinformed haha 😅, thank you so much for pointing that out to me. 

So using the [aries-framework-javascript](https://github.com/hyperledger/aries-framework-javascript) and rn-indy-sdk, I should be able to set up a mobile agent which can communicate with other agents through a mediator right? 
I understand that it's still under development so just wanted to know as of now what all can be achieved on the Mobile Agent side using the two.

I will be taking a look at [aries-agent-test-harness](https://github.com/hyperledger/aries-agent-test-harness), thank you for mentioning it.

**Comment by sairanjit** [comment]
Hey @TimoGlastra @karimStekelenburg @TheArhaam it's running now perfectly from https://github.com/AbsaOSS/rn-indy-sdk/issues/11#issuecomment-699627750
