### ISSUE TITLE
Can't connect to pool

### ISSUE THREAD

**Issue by ggalejandro** [AbsaOSS/rn-indy-sdk#13]
If we try to connect to a pool, after generate the config string and persist it to a file, if we use the methods indy.createPoolLedgerConfig or indy.openPoolLedger who both need a name and a string, they never end their executions.

We have tried to pass them the config string, and the path to the saved file. Same result. In addition, they don't throw any error.

Could you help? 
Thanks in advance

**Comment by jakubkoci** [comment]
What version of React Native project do you have? I had a problem with the version 0.62.x and higher. There is an issue about it https://github.com/react-native-community/upgrade-support/issues/114

**Comment by jakubkoci** [comment]
It's probably related to https://github.com/hyperledger/indy-sdk/issues/2346. 

I'm closing the issue now. This repo is being archived. Issues will be managed in the new repository [indy-sdk-react-native](https://github.com/hyperledger/indy-sdk-react-native). If the issue re-occurs, report it there, please.
