### ISSUE TITLE
rn-indy-sdk errors do not match indy-sdk errors

### ISSUE THREAD

**Issue by TimoGlastra** [AbsaOSS/rn-indy-sdk#21]
## Problem 

Errors thrown by rn-indy-sdk do not have the same signature as errors thrown by indy-sdk. For example in aries-framework-javscript when an error is thrown when trying to create a wallet we [check whether the `indyName` of the error is `WalletAlreadyExistsError`](https://github.com/hyperledger/aries-framework-javascript/blob/458363cb965973bc6a740d93a5a48da4402afc15/src/lib/wallet/IndyWallet.ts#L23-L32). However the same error in rn-indy-sdk does not have the property `indyName` and therefore aries-framework-javascript will crash (see image and  `Unhandled promise rejection below`)

```
'Unhandled promise rejection', [Error: {"code":"203","message":"org.hyperledger.indy.sdk.wallet.WalletExistsException: A wallet with the specified name already exists."}]
```

![image](https://user-images.githubusercontent.com/23165168/97704076-02e51300-1ab2-11eb-9e0c-eb102a8c003a.png)

## How to Solve 
We discussed during aries-framework-javascript call and came to the conclusion we need to update `IndySdkRejectResponse` class (on Android side, not looked at iOS yet) to match the indy-sdk for NodeJS error.

https://github.com/AbsaOSS/rn-indy-sdk/blob/43aff51c158cb871c12ce4247aa7df74690e51da/android/src/main/java/com/reactlibrary/IndySdkModule.java#L730-L765

**Comment by TimoGlastra** [comment]
@jakubkoci @karimStekelenburg

**Comment by TimoGlastra** [comment]
@thearhaam we figured out what the problem is with initialisation of the framework.

**Comment by TheArhaam** [comment]
@TimoGlastra Oh glad to know the problem was found 😄
