### ISSUE TITLE
Not able to run on iOS simluator

### ISSUE THREAD

**Issue by TimoGlastra** [AbsaOSS/rn-indy-sdk#43]
The current indy builds do not allow to run rn-indy-sdk on a simulator. This is more of an Indy issue, but tracking here for convenience

**Comment by jakubkoci** [comment]
I'm closing the issue in favor of hyperledger/indy-sdk-react-native#9. This repository is being archived.

**Comment by jakubkoci** [comment]
I'm closing the issue in favor of hyperledger/indy-sdk-react-native#9. This repository is being archived.
